### ISSUE TITLE
Drop testing support for Python 3.8 and add 3.13

### ISSUE THREAD

**Issue by zdc217** [techservicesillinois/awscli-login#218]
https://devguide.python.org/versions/ indicates that Python 3.8 is no longer supported and that 3.13 was released on 10/7/2024. 

The test matrix should be updated to remove 3.8 and add 3.13.

## Tasks

- [ ] remove 3.8 and add 3.13 to the Makefile - https://github.com/techservicesillinois/awscli-login/blob/49fa7dde622e0d0a1e60e969d739bde3dae22c61/Makefile#L85
- [ ] update the CI/CD workflow - https://github.com/techservicesillinois/awscli-login/blob/49fa7dde622e0d0a1e60e969d739bde3dae22c61/.github/workflows/cicd.yml#L71
- [ ] update tox.ini - https://github.com/techservicesillinois/awscli-login/blob/master/tox.ini

Note: We will update the end-of-life date in #225

**Comment by edthedev** [comment]
Heh. Good cleanup, bot, but we still want to have this discussion.
