### ISSUE TITLE
Add a developer guide `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/awscli-login#226]
## Tasks

- [x] add steps to setup for local development
- [x] how to build and install the product locally
- [x] add instructions for how (and why) to run each test suite
- [x] running the unit tests
- [ ] ~integration testing on AWS CLI V1~
- [ ] ~integration testing on AWS CLI V2~
- [ ] ~how to publish manually (in case CI/CD fails)~
