### ISSUE TITLE
Increased logging around session refresh failure

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/awscli-login#88]
## Tasks 

+ [ ] Review #76 for further context.
+ [ ] Review the code where a session is refreshed
+ [ ] add debug or info level log messages to notable places in the code for future reference.

## Context

@edthedev, it may indeed be the same issue, but I defer to @ddriddle to merge the issues if he agrees. He and I haven't looked over the code together or spoken about this issue other than superficially for a _long_ time, probably not since the collapse of the Roman Empire. ;-) 

The first thing I would suggest is that there probably isn't sufficient logging detail to see what's happening, and there does not now seem to be a traceback produced by the daemon crashing (if indeed that's what's happened).

Does the plugin have debug-level log messages, and can a user activate that from the plugin's configuration file or command-line? I'm happy to play guinea pig, but there is not enough information now available to trace what's going on.

_Originally posted by @JonRoma in https://github.com/techservicesillinois/awscli-login/issues/76#issuecomment-789382349_

**Comment by ddriddle** [comment]
@edthedev I'm closing this issue because it will no longer be relevant in the next release. The daemon is being removed so this type of bug will no long be possible.
