### ISSUE TITLE
Analysis for AWS CLI V2 adoption path

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/awscli-login#97]
## Tasks

+ [ ] inventory the current challenges and open new issues for each.
+ [ ] add any known work-arounds to the new issues as comments (keeping them open).
+ [ ] update #96 with status and any recommended work-arounds.
+ [ ] update the README with a recommended work-around.

**Comment by edthedev** [comment]
Added task level issues for some upcoming analysis.
