### ISSUE TITLE
inventory the current challenges for AWS CLI V2 and open new issues for each.

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/awscli-login#99]
## Tasks

- [ ] write a trivial manual command line test sequence using AWS CLI (still on v1)
- [ ] verify the trivial manual test works on a couple team member's machines
- [ ] upgrade to those team member's machines to V2
- [ ] re-run the trivial manual command line test sequence
- [ ] document results in a new issue

**Comment by edthedev** [comment]
Analysis is complete. Work will proceed in #103
